### ISSUE TITLE
need svg boring logo 

### ISSUE THREAD

**Issue by franswan** [boringprotocol/websitev2#1]

**Comment by redmanbravemm** [comment]
Do we have an internal styleguide or something similar to get the SVG logo from?

I've recently seen 
https://twitter.com/FranTiberious/status/1420349657092214792 👀

**Comment by franswan** [comment]
> Do we have an internal styleguide or something similar to get the SVG logo from?
> 
> I've recently seen
> https://twitter.com/FranTiberious/status/1420349657092214792 👀

I have made /static/img/boring-logo.svg 
It needs some drawing work done but is a start... I've not yet added it to the navigation. 

Internal styleguide: We might make a styleguide.njk to list out the "kitchen sink" of components, elements, colors.... 
The CSS variables govern only a few things as of yet. 
Tachyons styles are being used to prototype also so this is something to take into account as it's leaving a wake of utility classes behind it... I personally am ok with some liberty in this area but curious how you'd handle the CSS long term. 

I have intended that from this repo all style variables would be determined and would dictate to other projects a style guideline.

**Comment by redmanbravemm** [comment]
While browsing the existing Github issues I realized that I didn't replied you here. Sorry for that.

>I have made /static/img/boring-logo.svg
>It needs some drawing work done but is a start... I've not yet added it to the navigation.

Took a look and yes, it needs more work indeed. But shouldn't you have already a SVG replica of https://boringprotocol.io/assets/images/Logo.png? Or you don't so we need to recreate that as a vector?

--- 

I like Tachyons, it's highly customizable and I think we can heavily rely on it to build the future components we need for the BOP user interface. But before that, we need a color scheme, a custom SVG symbols icon system maybe, some design guideliness etc.

The well written documentation is a big plus, as for every library such as Bootstrap, Tailwinds etc. One thing we need to take care of is to use a custom build in order to serve just the bits we need from Tachyons, mostly helpers, and not the entire library.

**Comment by franswan** [comment]
I agree. Maybe we can use purge-css or something on Tachyons. The existing stylus configuration will need some attention and maybe remove in place for a sass variables set-up that would inform the Tachyons CSS. 

I've added a font that will makes matters more complex so we'll need to make sure our font-weighting will play nicely with the CSS rules. fw1 means 400 weight as it is now. maybe we do fw1, fw2, --- fw8 = 100, 200, -- 800

probably 4 weights will suffice. Let's see what we can come up with. See the font here: https://github.com/JetBrains/JetBrainsMono

**Comment by franswan** [comment]
Also, we do as you say, need to find an svg icon library...

**Comment by redmanbravemm** [comment]
> Also, we do as you say, need to find an svg icon library...

Actually, I'm thinking in building an SVG icon system ourselves, it's not like we need hundreds of icons after all.
We'll choose the style, we'll chose the way we integrate the icons within our pages (I like them as `symbols` in SVG) etc

**Comment by franswan** [comment]
Nice. That would be ideal, I agree. bop-icons, custom...

**Comment by franswan** [comment]
I'm going to close this issue as the original purpose has been fulfilled. See boringprotocol/brand/ for the logo in svg format. We can use that source for our purposes here in the website. We can open another issue to deal with further svg work such as an svg boring icon library.
